
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maidiepqrcyxmvapvins.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1haWRpZXBxcmN5eG12YXB2aW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDA3MjgsImV4cCI6MjA2MjIxNjcyOH0.F7IxgNJFZ2ixcGtZmCveuk_aoqpX7xOolulRPM6QefE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a more flexible client that allows access to tables not defined in the types
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to bypass TypeScript restrictions for tables not in the schema yet
export const fromTable = (tableName: string) => {
  return supabase.from(tableName as any);
};
