// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwfmzqktiocbhrsmxvvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Zm16cWt0aW9jYmhyc214dnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDc4MjYsImV4cCI6MjA2MTgyMzgyNn0.Uut5SCy2SsUdddA-IuKd1F8hvIC9f9-SHmVCLD2_XrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);